services:
  back:
    build:
      context: "."
      dockerfile: Dockerfile
      target: development
    working_dir: /app
    platform: ${BUILD_PLATFORM:-}
    command: ["yarn", "dev"]
    container_name: back
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
      - app:/app/node_modules
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/ladespen
      - DEFINED_USERNAME=user
      - DEFINED_PASSWORD=password
      - JWT_SECRET=secret

  front:
    build:
      context: "../ladespensita"
      dockerfile: Dockerfile
      target: production
    working_dir: /front
    platform: ${BUILD_PLATFORM:-}
    container_name: front
    ports:
      - "5173:5173"
    depends_on:
      - back
    volumes:
      - ../ladespensita:/front
      - front:/front/node_modules
    environment:
      - VITE_API_HOST=http://localhost:3000
  postgres:
    image: postgres:17
    platform: ${BUILD_PLATFORM:-}
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ladespen
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./assets/pgdata:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./assets/pgdata
  app:
  front:
