export const PRODUCTO_MODEL = "PRODUCTO_MODEL";
export const ALQUILER_MODEL = "ALQUILER_MODEL";
export const ALQUILERPRODUCTO_MODEL = "ALQUILERPRODUCTO_MODEL";
export const IMAGE_MODEL = "IMAGE_MODEL";
export const DB_CONNECTION = "DB_CONNECTION";
